# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/masahiko/Programs/HFMD_evaluate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/masahiko/Programs/HFMD_evaluate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/masahiko/Programs/HFMD_evaluate/CMakeFiles /home/masahiko/Programs/HFMD_evaluate/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/masahiko/Programs/HFMD_evaluate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named learning

# Build rule for target.
learning: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learning
.PHONY : learning

# fast build rule for target.
learning/fast:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/build
.PHONY : learning/fast

#=============================================================================
# Target rules for targets named objectPoseEstimation

# Build rule for target.
objectPoseEstimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectPoseEstimation
.PHONY : objectPoseEstimation

# fast build rule for target.
objectPoseEstimation/fast:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/build
.PHONY : objectPoseEstimation/fast

source/CRForest.o: source/CRForest.cpp.o
.PHONY : source/CRForest.o

# target to build an object file
source/CRForest.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/CRForest.cpp.o
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/CRForest.cpp.o
.PHONY : source/CRForest.cpp.o

source/CRForest.i: source/CRForest.cpp.i
.PHONY : source/CRForest.i

# target to preprocess a source file
source/CRForest.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/CRForest.cpp.i
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/CRForest.cpp.i
.PHONY : source/CRForest.cpp.i

source/CRForest.s: source/CRForest.cpp.s
.PHONY : source/CRForest.s

# target to generate assembly for a file
source/CRForest.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/CRForest.cpp.s
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/CRForest.cpp.s
.PHONY : source/CRForest.cpp.s

source/CRTree.o: source/CRTree.cpp.o
.PHONY : source/CRTree.o

# target to build an object file
source/CRTree.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/CRTree.cpp.o
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/CRTree.cpp.o
.PHONY : source/CRTree.cpp.o

source/CRTree.i: source/CRTree.cpp.i
.PHONY : source/CRTree.i

# target to preprocess a source file
source/CRTree.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/CRTree.cpp.i
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/CRTree.cpp.i
.PHONY : source/CRTree.cpp.i

source/CRTree.s: source/CRTree.cpp.s
.PHONY : source/CRTree.s

# target to generate assembly for a file
source/CRTree.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/CRTree.cpp.s
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/CRTree.cpp.s
.PHONY : source/CRTree.cpp.s

source/HoG.o: source/HoG.cpp.o
.PHONY : source/HoG.o

# target to build an object file
source/HoG.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/HoG.cpp.o
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/HoG.cpp.o
.PHONY : source/HoG.cpp.o

source/HoG.i: source/HoG.cpp.i
.PHONY : source/HoG.i

# target to preprocess a source file
source/HoG.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/HoG.cpp.i
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/HoG.cpp.i
.PHONY : source/HoG.cpp.i

source/HoG.s: source/HoG.cpp.s
.PHONY : source/HoG.s

# target to generate assembly for a file
source/HoG.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/HoG.cpp.s
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/HoG.cpp.s
.PHONY : source/HoG.cpp.s

source/learning.o: source/learning.cpp.o
.PHONY : source/learning.o

# target to build an object file
source/learning.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/learning.cpp.o
.PHONY : source/learning.cpp.o

source/learning.i: source/learning.cpp.i
.PHONY : source/learning.i

# target to preprocess a source file
source/learning.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/learning.cpp.i
.PHONY : source/learning.cpp.i

source/learning.s: source/learning.cpp.s
.PHONY : source/learning.s

# target to generate assembly for a file
source/learning.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/learning.cpp.s
.PHONY : source/learning.cpp.s

source/objectPoseEstimation.o: source/objectPoseEstimation.cpp.o
.PHONY : source/objectPoseEstimation.o

# target to build an object file
source/objectPoseEstimation.cpp.o:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/objectPoseEstimation.cpp.o
.PHONY : source/objectPoseEstimation.cpp.o

source/objectPoseEstimation.i: source/objectPoseEstimation.cpp.i
.PHONY : source/objectPoseEstimation.i

# target to preprocess a source file
source/objectPoseEstimation.cpp.i:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/objectPoseEstimation.cpp.i
.PHONY : source/objectPoseEstimation.cpp.i

source/objectPoseEstimation.s: source/objectPoseEstimation.cpp.s
.PHONY : source/objectPoseEstimation.s

# target to generate assembly for a file
source/objectPoseEstimation.cpp.s:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/objectPoseEstimation.cpp.s
.PHONY : source/objectPoseEstimation.cpp.s

source/util.o: source/util.cpp.o
.PHONY : source/util.o

# target to build an object file
source/util.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/util.cpp.o
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/util.cpp.o
.PHONY : source/util.cpp.o

source/util.i: source/util.cpp.i
.PHONY : source/util.i

# target to preprocess a source file
source/util.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/util.cpp.i
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/util.cpp.i
.PHONY : source/util.cpp.i

source/util.s: source/util.cpp.s
.PHONY : source/util.s

# target to generate assembly for a file
source/util.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/source/util.cpp.s
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/source/util.cpp.s
.PHONY : source/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... learning"
	@echo "... objectPoseEstimation"
	@echo "... rebuild_cache"
	@echo "... source/CRForest.o"
	@echo "... source/CRForest.i"
	@echo "... source/CRForest.s"
	@echo "... source/CRTree.o"
	@echo "... source/CRTree.i"
	@echo "... source/CRTree.s"
	@echo "... source/HoG.o"
	@echo "... source/HoG.i"
	@echo "... source/HoG.s"
	@echo "... source/learning.o"
	@echo "... source/learning.i"
	@echo "... source/learning.s"
	@echo "... source/objectPoseEstimation.o"
	@echo "... source/objectPoseEstimation.i"
	@echo "... source/objectPoseEstimation.s"
	@echo "... source/util.o"
	@echo "... source/util.i"
	@echo "... source/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

